export const skills = [
    {
        name: "HTML",
        info: "HTML (Hypertext Markup Language) is the standard markup language used to create web pages. It forms the structural layer of web design, allowing for the organization and presentation of content on the internet.",
        category: "Frontend",
        subCategory: "Code Language",
    },
    {
        name: "JSX",
        info: "JSX is a syntax extension for JavaScript, commonly used with React. It allows developers to write HTML structures in the same file as JavaScript code, making the creation of UI components more intuitive and efficient.",
        category: "Frontend",
        subCategory: "Code Language",
    },
    {
        name: "SEO practices",
        info: "SEO practices involve strategies to improve a website's visibility in search engine results. It includes optimizing content, improving site speed, and ensuring mobile responsiveness to rank higher on search engines like Google.",
        category: "Frontend",
        subCategory: "Web Optimization",
    },
    {
        name: "CSS",
        info: "CSS (Cascading Style Sheets) is a stylesheet language used to describe the presentation of a document written in HTML. It enables the separation of content from design, allowing for more flexibility and control in web development.",
        category: "Frontend",
        subCategory: "Styling Language",
    },
    {
        name: "JavaScript",
        info: "JavaScript is a versatile programming language used to create dynamic and interactive elements on websites. It's a core part of web development, allowing for client-side script writing to enhance user experience.",
        category: "Frontend",
        subCategory: "Programming Language",
    },
    {
        name: "TypeScript",
        info: "TypeScript is a superset of JavaScript that adds static typing abilities. This feature helps in catching errors early during development, leading to more robust and maintainable code, especially in large-scale applications.",
        category: "Frontend",
        subCategory: "Programming Language",
    },
    {
        name: "CSS/JS animations",
        info: "CSS/JS animations refer to the techniques used to create motion and visual transitions on web pages. These animations enhance user interface and experience by making web interactions more engaging and dynamic.",
        category: "Frontend",
        subCategory: "Web Animation",
    },
    {
        name: "NextJS",
        info: "NextJS is a React framework that enables functionality such as server-side rendering and generating static websites. It's known for its ease of use, performance improvements, and SEO-friendly features.",
        category: "Frontend",
        subCategory: "JavaScript Framework",
    },
    {
        name: "ReactJS",
        info: "ReactJS is a popular JavaScript library for building user interfaces, especially single-page applications. It's known for its component-based architecture, which helps in creating reusable UI components.",
        category: "Frontend",
        subCategory: "JavaScript Library",
    },
    {
        name: "Framer-motion",
        info: "Framer-motion is a library for React that makes creating realistic animations and gestures straightforward. It provides a powerful and easy-to-use set of tools for animating interfaces, improving user interaction and feedback.",
        category: "Frontend",
        subCategory: "Animation Library",
    },
    {
        name: "UI design",
        info: "UI design focuses on the visual elements of a user interface, such as buttons, icons, spacing, and color schemes. It plays a critical role in enhancing the usability and aesthetic appeal of digital products.",
        category: "Design",
        subCategory: "Web Design",
    },
    {
        name: "UX principles",
        info: "UX principles are guidelines that ensure a website or application is easy and pleasant to use. These principles focus on optimizing user satisfaction by improving usability, accessibility, and the overall user experience.",
        category: "Design",
        subCategory: "Web Design",
    },
    {
        name: "API / RestAPI",
        info: "APIs (Application Programming Interfaces) and REST APIs facilitate communication between software applications. They define a set of rules and protocols for building and interacting with software applications, making them essential for modern web development.",
        category: "Backend",
        subCategory: "Application Interface",
    },
    {
        name: "Responsive design",
        info: "Responsive design refers to the approach in web design where websites adjust seamlessly to the size of various devices' screens. This ensures optimal viewing and interaction experience across a range of devices.",
        category: "Frontend",
        subCategory: "Web Design",
    },
    {
        name: "TailwindCSS",
        info: "TailwindCSS is a utility-first CSS framework for rapidly building custom designs. It provides low-level utility classes that can be composed to build any design directly in your markup.",
        category: "Frontend",
        subCategory: "CSS Framework",
    },
    {
        name: "Wireframing",
        info: "Wireframing is a practice used to define and plan the structural framework of digital interfaces. It's a crucial step in UI/UX design, as it lays the foundation for the layout, functionality, and user journey.",
        category: "Design",
        subCategory: "Web Design",
    },

    {
        name: "Figma",
        info: "Figma is a cloud-based design tool used for UI and UX design. It's notable for its collaborative features, allowing multiple team members to work simultaneously on a design project.",
        category: "Design",
        subCategory: "Design Tool",
    },
    {
        name: "npm / yarn",
        info: "npm (Node Package Manager) and Yarn are package managers for JavaScript, simplifying the process of managing project dependencies and publishing JavaScript packages.",
        category: "Frontend",
        subCategory: "Package Managers",
    },
    {
        name: "SQL",
        info: "SQL (Structured Query Language) is a programming language used for managing and manipulating relational databases. It allows for storing, retrieving, updating, and deleting database data, making it essential for database management.",
        category: "Backend",
        subCategory: "Database Language",
    },
    {
        name: "Firebase",
        info: "Firebase is a platform developed by Google for creating mobile and web applications. It provides tools for tracking analytics, reporting and fixing app crashes, creating marketing and product experiment.",
        category: "Backend",
        subCategory: "Database/Backend-as-a-Service",
    },
    {
        name: "Supabase",
        info: "Supabase is an open-source Firebase alternative, providing database and authentication solutions for rapid web and mobile development. It's known for its real-time capabilities and scalable backend.",
        category: "Backend",
        subCategory: "Database/Backend-as-a-Service",
    },
    {
        name: "Git",
        info: "Git is a distributed version control system that enables developers to track changes in source code during software development. It's designed for coordinating work among programmers, but it can be used to track changes in any set of files.",
        category: "Version Control",
        subCategory: "Version Control System",
    },
    {
        name: "Branch-management",
        info: "Branch management in Git refers to the practice of managing branches in a code repository, allowing multiple developers to work simultaneously without interfering with each other's progress.",
        category: "Version Control",
        subCategory: "Version Control System",
    },
    {
        name: "Headless CMS (WordPress, Strapi)",
        info: "Headless CMS like WordPress and Strapi provide backend content management capabilities without a front-end interface. They deliver content through an API, offering greater flexibility in presenting content across various platforms.",
        category: "Backend",
        subCategory: "Content Management System",
    },
    {
        name: "WordPress",
        info: "WordPress is a popular content management system known for its user-friendly interface and flexibility. It's widely used for blogging, e-commerce, and business websites, offering extensive customization through themes and plugins.",
        category: "Backend",
        subCategory: "Content Management System",
    },
    {
        name: "NodeJs",
        info: "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. It allows developers to build scalable network applications using JavaScript on the server-side.",
        category: "Backend",
        subCategory: "JavaScript Runtime",
    },
    {
        name: "Php/MySQL",
        info: "PHP is a server-side scripting language, and MySQL is a relational database management system. Together, they are frequently used to create dynamic content on websites, with PHP handling the server-side logic and MySQL managing the data.",
        category: "Backend",
        subCategory: "Web Development Stack",
    },
    {
        name: "DB modelling",
        info: "Database modeling involves the creation of a database structure that reflects real-world entities and relationships. This process is crucial for efficient data storage, retrieval, and management in software applications.",
        category: "Backend",
        subCategory: "Database Design",
    },
];
